# ============================================================
# MLAI v3.5.2 MARKET STRUCTURE OUTCOME VALIDATION
# ============================================================
#
# PURPOSE
# -------
#
# Test whether the EXACT market-structure observations
# generated by MLAI v3.5.1 have measurable association
# with FUTURE price outcomes.
#
# IMPORTANT:
#
# v3.5.2 DOES NOT rebuild the structure detector.
#
# It imports the already-tested v3.5.1 experiment and reuses:
#
#     normalized_candles
#     classified_swings
#     structure_events
#     SWING_LOOKBACK
#
# This prevents v3.5.2 from accidentally using a different
# structure definition.
#
# ============================================================
#
# PROTECTION
# ----------
#
# market_data.bin        = READ ONLY
# Production MLAI        = NOT MODIFIED
# Learning memory        = NOT MODIFIED
# Trading                = DISABLED
#
# ============================================================
#
# SCIENTIFIC WARNING
# ------------------
#
# A swing is retrospective.
#
# Example:
#
# Candidate swing index = 100
# SWING_LOOKBACK = 3
#
# The swing is not known at candle 100.
# It becomes confirmable only after the required future
# candles exist.
#
# Therefore:
#
#     Swing signal time = confirmation time
#
# not:
#
#     Swing signal time = swing center
#
# This prevents a major look-ahead error.
#
# BOS / CHoCH events are evaluated at their actual event
# index because the event itself is generated from a close
# breaking a previously confirmed structural level.
#
# ============================================================


from collections import defaultdict
from pathlib import Path
import runpy
import math


# ============================================================
# CONFIGURATION
# ============================================================

STRUCTURE_TEST_HORIZONS = (
    4,
    8,
    16,
)

MIN_OBSERVATIONS = 10

SOURCE_FILE = (
    "mlai_v35_market_structure_test.py"
)


# ============================================================
# HEADER
# ============================================================

print()
print("=" * 80)
print("MLAI v3.5.2 MARKET STRUCTURE OUTCOME VALIDATION")
print("=" * 80)

print()
print("PURPOSE")
print("-------")
print()
print(
    "Test whether the exact market-structure observations "
    "generated by MLAI v3.5.1 contain measurable association "
    "with future price outcomes."
)

print()
print(
    "market_data.bin        = READ ONLY"
)
print(
    "Production MLAI        = NOT MODIFIED"
)
print(
    "Learning memory        = NOT MODIFIED"
)
print(
    "Trading                = DISABLED"
)


# ============================================================
# SOURCE FILE CHECK
# ============================================================

source_path = Path(
    SOURCE_FILE
)

if not source_path.exists():

    raise FileNotFoundError(
        f"Required source file not found: "
        f"{SOURCE_FILE}"
    )


# ============================================================
# LOAD EXACT v3.5.1 RESULTS
# ============================================================
#
# runpy executes v3.5.1 as a separate namespace.
#
# We intentionally do NOT modify that file.
#
# The purpose is to reuse its exact structure detection
# output instead of duplicating or guessing its logic.
#
# ============================================================

print()
print("=" * 80)
print("LOADING v3.5.1 STRUCTURE RESULTS")
print("=" * 80)

print()
print(
    f"Source: {SOURCE_FILE}"
)

print(
    "Mode  : READ / DIAGNOSTIC ONLY"
)


v351_namespace = runpy.run_path(
    str(source_path),
    run_name="__mlai_v351_diagnostic__"
)


# ============================================================
# REQUIRED VARIABLES
# ============================================================

required_variables = (

    "normalized_candles",

    "classified_swings",

    "structure_events",

)


missing_variables = [

    name

    for name in required_variables

    if name not in v351_namespace

]


if missing_variables:

    raise RuntimeError(
        "v3.5.1 did not expose the required "
        "structure variables: "
        + ", ".join(missing_variables)
    )


normalized_candles = v351_namespace[
    "normalized_candles"
]

classified_swings = v351_namespace[
    "classified_swings"
]

structure_events = v351_namespace[
    "structure_events"
]


SWING_LOOKBACK = v351_namespace.get(
    "SWING_LOOKBACK",
    None
)


# ============================================================
# BASIC DATA CHECK
# ============================================================

if not normalized_candles:

    raise RuntimeError(
        "normalized_candles is empty."
    )


print()
print("=" * 80)
print("v3.5.1 DATA IMPORT CHECK")
print("=" * 80)

print(
    "Candles:",
    len(normalized_candles)
)

print(
    "Classified swings:",
    len(classified_swings)
)

print(
    "Structure events:",
    len(structure_events)
)

if SWING_LOOKBACK is not None:

    print(
        "SWING_LOOKBACK:",
        SWING_LOOKBACK
    )

else:

    print(
        "SWING_LOOKBACK: NOT EXPOSED"
    )


# ============================================================
# FUTURE OUTCOME
# ============================================================

def get_future_outcome(
    candles,
    index,
    horizon
):

    future_index = (
        index + horizon
    )

    if (
        index < 0
        or index >= len(candles)
    ):

        return None

    if future_index >= len(candles):

        return None

    current_close = candles[
        index
    ]["close"]

    future_close = candles[
        future_index
    ]["close"]

    if future_close > current_close:

        return "UP"

    if future_close < current_close:

        return "DOWN"

    return "NEUTRAL"


# ============================================================
# OUTCOME SUMMARY
# ============================================================

def summarize_outcomes(
    outcomes
):

    total = len(outcomes)

    if total == 0:

        return {
            "total": 0,
            "up": 0,
            "down": 0,
            "neutral": 0,
            "up_rate": 0.0,
            "down_rate": 0.0,
            "neutral_rate": 0.0,
        }

    up = outcomes.count(
        "UP"
    )

    down = outcomes.count(
        "DOWN"
    )

    neutral = outcomes.count(
        "NEUTRAL"
    )

    return {

        "total": total,

        "up": up,

        "down": down,

        "neutral": neutral,

        "up_rate":
            up / total,

        "down_rate":
            down / total,

        "neutral_rate":
            neutral / total,

    }


# ============================================================
# SWING CONFIRMATION INDEX
# ============================================================

def get_swing_signal_index(
    swing
):

    # --------------------------------------------------------
    # Prefer an explicitly stored confirmation index.
    # --------------------------------------------------------

    for key in (
        "confirmation_index",
        "confirmed_index",
        "confirm_index",
    ):

        value = swing.get(
            key
        )

        if isinstance(
            value,
            int
        ):

            return value


    # --------------------------------------------------------
    # Otherwise reconstruct confirmation index from the
    # exact SWING_LOOKBACK used by v3.5.1.
    # --------------------------------------------------------

    swing_index = swing.get(
        "index"
    )

    if swing_index is None:

        return None


    if SWING_LOOKBACK is None:

        raise RuntimeError(
            "SWING_LOOKBACK is not exposed by "
            "v3.5.1 and swing confirmation index "
            "is not stored in the swing record."
        )


    return (
        swing_index
        + SWING_LOOKBACK
    )


# ============================================================
# STRUCTURE SIGNAL COLLECTION
# ============================================================

structure_signals = defaultdict(
    list
)


# ============================================================
# SWING SIGNALS
# ============================================================

for swing in classified_swings:

    swing_type = swing.get(
        "structure"
    )

    if swing_type not in (
        "HH",
        "HL",
        "LH",
        "LL",
    ):

        continue


    signal_index = (
        get_swing_signal_index(
            swing
        )
    )

    if signal_index is None:

        continue


    if (
        signal_index < 0
        or signal_index >= len(
            normalized_candles
        )
    ):

        continue


    structure_signals[
        swing_type
    ].append({

        "index":
            signal_index,

        "swing_index":
            swing.get("index"),

        "type":
            swing_type,

        "source":
            "SWING",

    })


# ============================================================
# BOS / CHoCH SIGNALS
# ============================================================

for event in structure_events:

    event_type = event.get(
        "type"
    )

    if event_type not in (
        "BOS_BULLISH",
        "BOS_BEARISH",
        "CHoCH_BULLISH",
        "CHoCH_BEARISH",
    ):

        continue


    signal_index = event.get(
        "index"
    )

    if signal_index is None:

        continue


    if (
        signal_index < 0
        or signal_index >= len(
            normalized_candles
        )
    ):

        continue


    structure_signals[
        event_type
    ].append({

        "index":
            signal_index,

        "type":
            event_type,

        "source":
            "EVENT",

    })


# ============================================================
# SIGNAL COUNTS
# ============================================================

print()
print("=" * 80)
print("VALID STRUCTURE SIGNALS")
print("=" * 80)


for signal_type in (
    "HH",
    "HL",
    "LH",
    "LL",
    "BOS_BULLISH",
    "BOS_BEARISH",
    "CHoCH_BULLISH",
    "CHoCH_BEARISH",
):

    print(
        f"{signal_type:<18}"
        f"{len(structure_signals.get(signal_type, []))}"
    )


# ============================================================
# GLOBAL BASELINE
# ============================================================

print()
print("=" * 80)
print("GLOBAL FUTURE-MOVEMENT BASELINES")
print("=" * 80)


global_baselines = {}


for horizon in STRUCTURE_TEST_HORIZONS:

    outcomes = []

    for index in range(
        len(normalized_candles)
    ):

        outcome = get_future_outcome(
            normalized_candles,
            index,
            horizon
        )

        if outcome is not None:

            outcomes.append(
                outcome
            )


    summary = summarize_outcomes(
        outcomes
    )


    global_baselines[
        horizon
    ] = summary


    directional_total = (
        summary["up"]
        + summary["down"]
    )


    if directional_total > 0:

        majority = (
            max(
                summary["up"],
                summary["down"]
            )
            / directional_total
        )

    else:

        majority = None


    print()
    print(
        f"HORIZON: {horizon} CANDLES"
    )

    print(
        f"Records : {summary['total']}"
    )

    print(
        f"UP      : "
        f"{summary['up']} "
        f"({summary['up_rate']:.2%})"
    )

    print(
        f"DOWN    : "
        f"{summary['down']} "
        f"({summary['down_rate']:.2%})"
    )

    print(
        f"NEUTRAL : "
        f"{summary['neutral']} "
        f"({summary['neutral_rate']:.2%})"
    )

    if majority is not None:

        print(
            f"Directional majority baseline: "
            f"{majority:.2%}"
        )

    else:

        print(
            "Directional majority baseline: N/A"
        )


# ============================================================
# INDIVIDUAL STRUCTURE OUTCOME TEST
# ============================================================

print()
print("=" * 80)
print("INDIVIDUAL STRUCTURE OUTCOME TEST")
print("=" * 80)


structure_types = (

    "HH",
    "HL",
    "LH",
    "LL",

    "BOS_BULLISH",
    "BOS_BEARISH",

    "CHoCH_BULLISH",
    "CHoCH_BEARISH",

)


results = []


for horizon in STRUCTURE_TEST_HORIZONS:

    print()
    print(
        "=" * 80
    )

    print(
        f"HORIZON: {horizon} CANDLES"
    )

    print(
        "=" * 80
    )


    baseline = global_baselines[
        horizon
    ]


    baseline_directional_total = (
        baseline["up"]
        + baseline["down"]
    )


    if baseline_directional_total > 0:

        baseline_majority = (
            max(
                baseline["up"],
                baseline["down"]
            )
            / baseline_directional_total
        )

    else:

        baseline_majority = None


    for structure_type in structure_types:

        signals = structure_signals.get(
            structure_type,
            []
        )


        observations = []


        for signal in signals:

            index = signal[
                "index"
            ]


            outcome = get_future_outcome(
                normalized_candles,
                index,
                horizon
            )


            if outcome is not None:

                observations.append(
                    outcome
                )


        summary = summarize_outcomes(
            observations
        )


        total = summary[
            "total"
        ]


        if total == 0:

            print()

            print(
                f"{structure_type:<18}"
                "NO VALID OBSERVATIONS"
            )

            continue


        directional_total = (
            summary["up"]
            + summary["down"]
        )


        if directional_total > 0:

            majority_accuracy = (
                max(
                    summary["up"],
                    summary["down"]
                )
                / directional_total
            )

        else:

            majority_accuracy = None


        bullish_structures = (
            structure_type in (
                "HH",
                "HL",
                "BOS_BULLISH",
                "CHoCH_BULLISH",
            )
        )


        bearish_structures = (
            structure_type in (
                "LH",
                "LL",
                "BOS_BEARISH",
                "CHoCH_BEARISH",
            )
        )


        directional_correct = 0


        if bullish_structures:

            directional_correct = (
                summary["up"]
            )

        elif bearish_structures:

            directional_correct = (
                summary["down"]
            )


        directional_accuracy = None


        if directional_total > 0:

            directional_accuracy = (
                directional_correct
                / directional_total
            )


        baseline_difference = None


        if (
            directional_accuracy is not None
            and baseline_majority is not None
        ):

            baseline_difference = (
                directional_accuracy
                - baseline_majority
            )


        results.append({

            "structure":
                structure_type,

            "horizon":
                horizon,

            "observations":
                total,

            "up":
                summary["up"],

            "down":
                summary["down"],

            "neutral":
                summary["neutral"],

            "up_rate":
                summary["up_rate"],

            "down_rate":
                summary["down_rate"],

            "neutral_rate":
                summary["neutral_rate"],

            "directional_accuracy":
                directional_accuracy,

            "baseline":
                baseline_majority,

            "difference":
                baseline_difference,

        })


        print()

        print(
            f"{structure_type:<18}"
            f"N={total:<5} "
            f"UP={summary['up_rate']:.2%} "
            f"DOWN={summary['down_rate']:.2%} "
            f"NEUTRAL={summary['neutral_rate']:.2%}"
        )


        if directional_accuracy is not None:

            difference_text = (
                f"{baseline_difference:+.2%}"
                if baseline_difference is not None
                else "N/A"
            )

            baseline_text = (
                f"{baseline_majority:.2%}"
                if baseline_majority is not None
                else "N/A"
            )

            print(
                f"{'':18}"
                f"Expected-direction accuracy="
                f"{directional_accuracy:.2%} "
                f"| Baseline="
                f"{baseline_text} "
                f"| Difference="
                f"{difference_text}"
            )


# ============================================================
# GROUP TEST
# ============================================================

def run_group_test(
    title,
    signal_types,
    expected_direction
):

    print()
    print("=" * 80)
    print(title)
    print("=" * 80)


    for horizon in STRUCTURE_TEST_HORIZONS:

        outcomes = []


        for signal_type in signal_types:

            for signal in structure_signals.get(
                signal_type,
                []
            ):

                outcome = get_future_outcome(
                    normalized_candles,
                    signal["index"],
                    horizon
                )


                if outcome is not None:

                    outcomes.append(
                        outcome
                    )


        summary = summarize_outcomes(
            outcomes
        )


        directional_total = (
            summary["up"]
            + summary["down"]
        )


        if directional_total > 0:

            if expected_direction == "UP":

                expected_accuracy = (
                    summary["up"]
                    / directional_total
                )

            else:

                expected_accuracy = (
                    summary["down"]
                    / directional_total
                )

        else:

            expected_accuracy = None


        baseline = global_baselines[
            horizon
        ]


        baseline_directional_total = (
            baseline["up"]
            + baseline["down"]
        )


        if baseline_directional_total > 0:

            baseline_accuracy = (
                max(
                    baseline["up"],
                    baseline["down"]
                )
                / baseline_directional_total
            )

        else:

            baseline_accuracy = None


        print()
        print(
            f"Horizon {horizon}"
        )

        print(
            f"Observations: "
            f"{summary['total']}"
        )

        print(
            f"Future UP: "
            f"{summary['up_rate']:.2%}"
        )

        print(
            f"Future DOWN: "
            f"{summary['down_rate']:.2%}"
        )

        print(
            f"Future NEUTRAL: "
            f"{summary['neutral_rate']:.2%}"
        )


        if expected_accuracy is not None:

            print(
                f"Expected-direction accuracy: "
                f"{expected_accuracy:.2%}"
            )


        if baseline_accuracy is not None:

            print(
                f"Baseline: "
                f"{baseline_accuracy:.2%}"
            )


        if (
            expected_accuracy is not None
            and baseline_accuracy is not None
        ):

            print(
                f"Difference vs baseline: "
                f"{expected_accuracy - baseline_accuracy:+.2%}"
            )


# ============================================================
# BULLISH STRUCTURE GROUP
# ============================================================

run_group_test(

    "BULLISH STRUCTURE GROUP",

    (
        "HH",
        "HL",
        "BOS_BULLISH",
        "CHoCH_BULLISH",
    ),

    "UP"

)


# ============================================================
# BEARISH STRUCTURE GROUP
# ============================================================

run_group_test(

    "BEARISH STRUCTURE GROUP",

    (
        "LH",
        "LL",
        "BOS_BEARISH",
        "CHoCH_BEARISH",
    ),

    "DOWN"

)


# ============================================================
# EVENT-ONLY TEST
# ============================================================

run_group_test(

    "BULLISH STRUCTURE EVENTS",

    (
        "BOS_BULLISH",
        "CHoCH_BULLISH",
    ),

    "UP"

)


run_group_test(

    "BEARISH STRUCTURE EVENTS",

    (
        "BOS_BEARISH",
        "CHoCH_BEARISH",
    ),

    "DOWN"

)


# ============================================================
# SAMPLE SIZE AUDIT
# ============================================================

print()
print("=" * 80)
print("SAMPLE SIZE AUDIT")
print("=" * 80)


for horizon in STRUCTURE_TEST_HORIZONS:

    print()
    print(
        f"HORIZON {horizon}"
    )


    for structure_type in structure_types:

        matching = [

            result

            for result in results

            if (
                result["structure"]
                == structure_type
                and result["horizon"]
                == horizon
            )

        ]


        if not matching:

            continue


        result = matching[0]


        n = result[
            "observations"
        ]


        if n < MIN_OBSERVATIONS:

            print(
                f"WARNING: "
                f"{structure_type:<18}"
                f"N={n} "
                f"is below minimum "
                f"reporting sample="
                f"{MIN_OBSERVATIONS}"
            )


# ============================================================
# LOOK-AHEAD AUDIT
# ============================================================

print()
print("=" * 80)
print("LOOK-AHEAD AUDIT")
print("=" * 80)


swing_count = 0
swing_adjusted_count = 0


for swing in classified_swings:

    if swing.get(
        "structure"
    ) not in (
        "HH",
        "HL",
        "LH",
        "LL",
    ):

        continue


    original_index = swing.get(
        "index"
    )


    signal_index = (
        get_swing_signal_index(
            swing
        )
    )


    if (
        original_index is None
        or signal_index is None
    ):

        continue


    swing_count += 1


    if signal_index > original_index:

        swing_adjusted_count += 1


print(
    f"Directional swings checked: "
    f"{swing_count}"
)


print(
    f"Swings shifted to confirmation: "
    f"{swing_adjusted_count}"
)


if (
    swing_count > 0
    and swing_adjusted_count == swing_count
):

    print(
        "PASS: All tested directional swings "
        "use confirmation timing."
    )

elif swing_count == 0:

    print(
        "WARNING: No directional swings available."
    )

else:

    print(
        "WARNING: Some swings were not shifted "
        "to a later confirmation point."
    )


# ============================================================
# IMPORTANT INTERPRETATION
# ============================================================

print()
print("=" * 80)
print("IMPORTANT INTERPRETATION")
print("=" * 80)

print(
    """
This experiment is DESCRIPTIVE.

It does NOT prove that market structure causes
future price movement.

The experiment asks:

    "After a structure observation became available,
     how frequently did price move UP, DOWN, or remain
     NEUTRAL over the tested future horizon?"

Important protections:

1. The exact v3.5.1 structure detector is reused.

2. The structure detector itself is NOT rewritten.

3. Swing observations are evaluated from their
   confirmation point rather than their retrospective
   center point whenever possible.

4. BOS / CHoCH events are evaluated from their event
   candle.

5. Future outcome data is only used AFTER the signal
   becomes available.

6. The global directional majority baseline is reported.

7. Small samples are explicitly flagged.

8. No structure rule is promoted to production.

9. No learning memory is updated.

10. No trading is performed.

11. Historical association is NOT the same as prediction.

12. This test is still NOT sufficient to establish
    generalization.

The scientifically stronger sequence remains:

    STRUCTURE DETECTION
            |
            v
    FUTURE OUTCOME TEST
            |
            v
    BASELINE COMPARISON
            |
            v
    CHRONOLOGICAL OUT-OF-SAMPLE TEST
            |
            v
    WALK-FORWARD VALIDATION
            |
            v
    MULTIPLE-TESTING CONTROL
            |
            v
    CALIBRATION
            |
            v
    STRUCTURE + CONTEXT
            |
            v
    HISTORICAL SIMILARITY
            |
            v
    PROBABILISTIC MARKET REASONING

Do NOT promote structure observations to production
knowledge merely because they look convincing historically.
"""
)


# ============================================================
# FINAL PROTECTION CHECK
# ============================================================

print()
print("=" * 80)
print("FINAL PROTECTION CHECK")
print("=" * 80)

print(
    "market_data.bin : READ ONLY"
)

print(
    "Production MLAI : NOT MODIFIED"
)

print(
    "Learning memory : NOT MODIFIED"
)

print(
    "Trading         : DISABLED"
)

print()
print("=" * 80)
print(
    "MLAI v3.5.2 MARKET STRUCTURE "
    "OUTCOME VALIDATION COMPLETE"
)
print("=" * 80)